# Generated by Django 4.2.2 on 2023-06-15 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_price', models.BigIntegerField()),
                ('image', models.ImageField(default='no_image.png', upload_to='pictures')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auction.item')),
                ('current_bid', models.BigIntegerField(null=True)),
                ('listed_date', models.DateField(auto_now_add=True)),
                ('deadline_date', models.DateField(default=django.utils.timezone.now)),
                ('last_updated', models.DateField(auto_now=True)),
                ('is_auction_open', models.BooleanField(default=True)),
                ('current_bid_owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
