# Generated by Django 4.2.2 on 2023-06-15 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 18, 0, 13, 611404, tzinfo=datetime.timezone.utc)),
        ),
    ]
