# Generated by Django 4.2.2 on 2023-06-15 18:02

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auction_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline_date',
            field=models.DateField(default=auction.models.Auction.seven_day_hence),
        ),
    ]
