# Generated by Django 4.2.2 on 2023-06-15 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0004_alter_auction_current_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_bid_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
